require("plugins.presence")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.harpoon")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.colhighlight")
require("plugins.weather")
require("plugins.dashboard")
-- require("plugins.feline")
